Repository whatwg/url, pull requests merged in 2020-05, with the labels that each got.

#497 Verify domain is not empty after "domain to ASCII"
  url.bs
Labels: topic: parser

#459 Forbid < and > in hosts
  url.bs
Labels: needs tests

#519 Define upper limit of a URL-port string
  url.bs
Labels: topic: validation
